services:
  # Backend API service
  - type: web
    name: tricolorify-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m gunicorn --chdir /opt/render/project/src/backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /
